name: my_data_state
description: A simple package to encapsulate the state of data (loading, loaded, exists, not exists)
version: 0.2.0
homepage: https://github.com/cedvdb/data_state

environment:
  sdk: '>=2.14.4 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
